### ISSUE TITLE
TypeError: e.resume is not a function

### ISSUE THREAD

**Issue by mike-lischke** [harold-b/vscode-duktape-debug#59]
With the latest extension version (0.5.6) I get now an error when I debug my own extension.:

```
Activating extension `HaroldBrenes.duk-debug` failed:  e.resume is not a function
extensionHostProcess.js:506
Here is the error stack:  TypeError: e.resume is not a function
	at S.start (/Users/mike/.vscode/extensions/haroldbrenes.duk-debug-0.5.6/dist/extension.js:1:64530)
	at Function.run (/Users/mike/.vscode/extensions/haroldbrenes.duk-debug-0.5.6/dist/extension.js:1:15675)
	at Object.<anonymous> (/Users/mike/.vscode/extensions/haroldbrenes.duk-debug-0.5.6/dist/extension.js:1:38869)
	at n (/Users/mike/.vscode/extensions/haroldbrenes.duk-debug-0.5.6/dist/extension.js:1:186)
	at /Users/mike/.vscode/extensions/haroldbrenes.duk-debug-0.5.6/dist/extension.js:1:985
	at Object.<anonymous> (/Users/mike/.vscode/extensions/haroldbrenes.duk-debug-0.5.6/dist/extension.js:1:995)
	at Module._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object..js (internal/modules/cjs/loader.js:798:10)
	at Module.load (internal/modules/cjs/loader.js:645:32)
	at Function.<anonymous> (internal/modules/cjs/loader.js:560:12)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
	at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at require (internal/modules/cjs/helpers.js:16:16)
	at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:32:963)
	at d._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:766:484)
	at d._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:677:300)
	at d._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:676:360)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:674:296)
	at Object._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:506:21)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:505:632
	at Array.map (<anonymous>)
	at Object._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:505:620)
	at Object.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:503:413)
	at d._activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:675:24)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:683:293
```

Additionally I get:

```
(node:97525) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning.js:27
(node:97525) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning.js:27
```

though I don't know if that is throw for the duktap-debug extension or comes from something else.

**Comment by andrewrch** [comment]
How are you debugging the extension? I updated the launch.json in the repo and there is no need to run the server now.

**Comment by mike-lischke** [comment]
The thing is: I don't debug your extension, but mine ([vscode-antlr4](https://github.com/mike-lischke/vscode-antlr4)), which has nothing to do with duktape. Still your debug extention is activated and produces this error.

**Comment by mike-lischke** [comment]
Have you removed your extension from the vscode marketplace? I had to disable your extension and now it's gone and I cannot re-install it.
